### ISSUE TITLE
How to disable SSL verification

### ISSUE THREAD

**Issue by 4Urban** [regadas/sqltools-trino-driver#213]
When trying to connect, I'm getting error message like `ERROR: Error selecting connection unable to verify the first certificate`.

Is there any way to disable SSL verification like the way in Python?
In Python, by just setting the argument to `False` like below, it's solved. ([Reference](https://github.com/trinodb/trino-python-client#ssl-verification))

```python
from trino.dbapi import connect
from trino.auth import BasicAuthentication

conn = connect(
    user="<username>",
    auth=BasicAuthentication("<username>", "<password>"),
    http_scheme="https",
    verify=False
)
```

**Comment by PmcFizz** [comment]
you can review this MR https://github.com/regadas/sqltools-trino-driver/pull/180。
this driver version is `0.2.9`。 dont support https links。 if you want support，you can modify code，and build your extension 。
 you need build a new [trino-client](https://github.com/regadas/trino-js-client) use main branch。 and replace 。
 
 good luck。

**Comment by regadas** [comment]
Hello! Thanks for bringing this up. Correct the trino-client already has support for this ... it's just pending a release which I should do soon. Once that's done I'll update the extension.

**Comment by 4Urban** [comment]
Thank you for the answer, both! It's glad to hear that it's gonna be possible soon.

**Comment by 4Urban** [comment]
Hello, @regadas ! Is there any update for this? I've seen that your code is released on https://github.com/regadas/trino-js-client/pull/203.

**Comment by maksim77** [comment]
Plus one vote in favor of this possibility!
Is there any news?

**Comment by wjhrdy** [comment]
adding my plus one for this! thanks for the hard work

**Comment by regadas** [comment]
Hello! Sorry for dropping the ball here. I'll take a look at this in the next few days. 👍

**Comment by regadas** [comment]
Hello! I quickly add this in the last release let me know if you see issues!
